# Generated by Django 5.1.3 on 2024-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('age', models.PositiveIntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Enterepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=123)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=132)),
            ],
        ),
    ]
