# Generated by Django 5.1.3 on 2024-11-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_enterepreneur_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterepreneur',
            name='customer',
            field=models.ForeignKey(default='Rwagasana', on_delete=django.db.models.deletion.CASCADE, to='app2.customers'),
        ),
    ]
