# Generated by Django 5.1.3 on 2024-11-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_enterepreneur_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='names',
            field=models.CharField(default='Rwagasana', max_length=50),
        ),
        migrations.AlterField(
            model_name='enterepreneur',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.customers'),
        ),
    ]
