# Generated by Django 5.1.3 on 2024-11-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_customers_names_alter_enterepreneur_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterepreneur',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customers',
            name='names',
            field=models.CharField(max_length=50),
        ),
    ]
